set cursorline
set nocompatible
"set t_Co=256
set bs=2
set wildmenu
set wildmode=list:longest
set ruler
set mouse=n
set nu
syntax on
set autoindent
"set clipboard=unamed
set listchars=tab:>·,trail:_
set list
set tabstop=4
set shiftwidth=4
set columns=86
colorscheme elflord
set completeopt=menuone,longest,preview
